import { ref} from "vue";
// Use export to let others file can access this array, but if we don't use export, the array is can be used only inside this file.
export const products = ref([
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},
{
 img: "/images/1.png",
 name: "Messi",
 type1: "A",
 type2: "B",
 start_date: "2024/08/29",
 duration: "3 months",
},

{
    img: "/images/1.png",
    name: "Messi",
    type1: "A",
    type2: "B",
    start_date: "2024/08/29",
    duration: "3 months",
   },
   {
    img: "/images/1.png",
    name: "Messi",
    type1: "A",
    type2: "B",
    start_date: "2024/08/29",
    duration: "3 months",
   },
   {
    img: "/images/1.png",
    name: "Messi",
    type1: "A",
    type2: "B",
    start_date: "2024/08/29",
    duration: "3 months",
   },
   {
    img: "/images/1.png",
    name: "Messi",
    type1: "A",
    type2: "B",
    start_date: "2024/08/29",
    duration: "3 months",
   },
   

{
    img: "/images/1.png",
    name: "Messi",
    type1: "A",
    type2: "B",
    start_date: "2024/08/29",
    duration: "3 months",
   },
   {
    img: "/images/1.png",
    name: "Messi",
    type1: "A",
    type2: "B",
    start_date: "2024/08/29",
    duration: "3 months",
   },
   {
    img: "/images/1.png",
    name: "Messi",
    type1: "A",
    type2: "B",
    start_date: "2024/08/29",
    duration: "3 months",
   },
   {
    img: "/images/1.png",
    name: "Messi",
    type1: "A",
    type2: "B",
    start_date: "2024/08/29",
    duration: "3 months",
   },
]);